import Head from 'next/head';
import { useEffect, useState } from 'react';
import axios from 'axios';
import Link from 'next/link';
import { makeStyles } from '@material-ui/core/styles';
import { Typography, Box, Grid, Card, CardContent, CardMedia } from '@material-ui/core';

const useStyles = makeStyles({
  main: {
    padding: '24px',
    backgroundColor: 'black',
  },
  media: {
    height: 0,
    paddingTop: '56.25%', // 16:9
  }
});


export default function Home() {
  const classes = useStyles();
  const [data, setData] = useState();

  const apiKey = 'HRhZabIEc8t1MbYzm8y0h91H5ecFOwMQrT4G8j25';
  const url = `https://api.nasa.gov/techtransfer/patent/?q=10&engine&api_key=${apiKey}`;

  const getTechTransferData = async () => {
    const res = await axios.get(url);
    const info = await res.data;
    console.log(info);
    setData(info);
  };

  useEffect(() => {
    getTechTransferData();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classes.main}>
        <Link href="/polychromatic">
          <Typography variant="h5" component="span" className="hoverable" style={{fontSize:"100px", color:"rgb(9, 161, 255)"}}>
            Polychromatic
          </Typography>
        </Link>
        {data && (
          <Grid container spacing={2} style={{margin: "50px 0 0 0"}}>
            {data.results.map((tech, index) => (
              <Grid item xs={12} sm={6} md={4} key={index}>
                <Card style={{minHeight:"700px"}}>
                  <CardMedia className={classes.media} image={tech[10]} title="Tech image" />
                  <CardContent>
                    <Typography gutterBottom variant="h6" component="h2">
                      {tech[1]}
                    </Typography>
                    <Typography variant="body2" color="textSecondary" component="p">
                      {tech[3]}
                    </Typography>
                  </CardContent>
                </Card>
              </Grid>
            ))}
          </Grid>
        )}
      </main>
    </>
  );
}
